apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 8 }}
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list"]